### PR TITLE
Add pre commit and linting

### PR DESCRIPTION
**Pull request by jeffmcutter**
- Add ansible-lint and pre-commit config files.
- Add pre-commit to requirements.txt.
- Add ansible-lint github workflow.
- Commit pre-commit and ansible-lint fixes excluding syntax_highlighting_demo.yml.

### CODE REVIEW

**Review by svor — APPROVED** [review]
@jeffmcutter thank you for the PR!
Please resolve the conflict and we are good to merge it

**Comment by svor** [comment]
@jeffmcutter I see that ansible-lint check was failed, could you please take a look

**Comment by jeffmcutter** [comment]
It's intentional for the demo of ansible-lint in VS Code and pre-commit.

**Comment by svor** [comment]
> It's intentional for the demo of ansible-lint in VS Code and pre-commit.
Got it, thanks!

I don't see how we can exclude syntax_highlighting_demo.yml file in ansible-lint workflow.
 
Maybe we can remove syntax_highlighting_demo.yml from the sample at all? I don't think it's important to have it. If we want to show how the linter works, we can open any playbook from the sample and make changes there.

Because right now the workflow isn't useful, we'll have it failed every time

@jeffmcutter WDYT?

**Comment by jeffmcutter** [comment]
How about I exclude that file from ansible-lint?  That way the pipeline can pass and if someone wants to demo/try the linting and pre-commit they can copy or rename the file.

**Review by svor — APPROVED** [review]

**Pull request merged**
